import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name:'Admin',
      email:'admin@example.com',
      password:bcrypt.hashSync('123456'),
      isAdmin:true,
    },
    {
      name:'Anagha',
      email:'abc@example.com',
      password:bcrypt.hashSync('123456'),
      isAdmin:false,
    }
  ],
  products: [
    {
     // _id: '1',
      name: 'Chair',
      slug: 'chair',
      cateogry: 'Furnitures',
      image: '/images/img1.jpg',
      price: 15000,
      countInStock: 10,
      brand: 'Star',
      rating: 4.5,
      numReviews: 10,
      description: 'Very comfortable chair',
    },
    {
      //_id: '2',
      name: 'Dining Table',
      slug: 'Dining Table',
      cateogry: 'Furnitures',
      image: '/images/img3.jpg',
      price: 25000,
      countInStock: 10,
      brand: 'Star',
      rating: 3.5,
      numReviews: 10,
      description: '6 Seater Dining table American Walnut Finish',
    },
    {
     // _id: '3',
      name: 'Watch',
      slug: 'watch',
      cateogry: 'Watches',
      image: '/images/img4.jpg',
      price: 18928,
      countInStock: 10,
      brand: 'Daniel Willington',
      rating: 5,
      numReviews: 10,
      description: 'Petite Melorse watch + Classic Bracelet',
    },
    {
     // _id: '4',
      name: 'Shoes',
      slug: 'Shoes',
      cateogry: 'Sports shoes',
      image: '/images/img5.jpg',
      price: 8740,
      countInStock: 7,
      brand: 'Nike',
      rating: 3,
      numReviews: 10,
      description: 'Very comfy and attractive shoes',
    },
    {
     // _id: '5',
      name: 'Light Lamp',
      slug: 'Light Lamp',
      cateogry: 'Household items',
      image: '/images/img6.jpg',
      price: 5400,
      countInStock: 5,
      brand: 'Star',
      rating: 3.9,
      numReviews: 10,
      description: 'White light lamp',
    },
    {
      //_id: '6',
      name: 'Coffee Mugs',
      slug: 'Coffee Mugs',
      cateogry: 'Crockeries',
      image: '/images/img7.jpg',
      price: 647,
      countInStock: 15,
      brand: 'Star',
      rating: 4.7,
      numReviews: 10,
      description: 'Black 6 pieces solid ceramic coffee mug',
    },
    {
      //_id: '7',
      name: 'Ear phones',
      slug: 'Ear phones',
      cateogry: 'Mobile Accessories',
      image: '/images/img8.jpg',
      price: 348,
      countInStock: 8,
      brand: 'Star',
      rating: 3.7,
      numReviews: 10,
      description: 'Boat BassHeads 100 In-Ear Wired Earphones',
    },
    {
      //_id: '8',
      name: 'Wall hangings',
      slug: 'Wall hangings',
      cateogry: 'Art work',
      image: '/images/img9.jpg',
      price: 699,
      countInStock: 12,
      brand: 'Star',
      rating: 4.1,
      numReviews: 10,
      description: 'Wooden Handicraft Wall Rack Shelves',
    },
  ],
};
export default data;
