const data = {
  products: [
    {
      name: 'Chair',
      slug: 'chair',
      cateogry: 'Furnitures',
      image: '/images/img1.jpg',
      price: 15000,
      countInStock: 10,
      brand: 'Star',
      rating: 4.5,
      numReviews: 10,
      description: 'Very comfortable chair',
    },
    {
      name: 'Dining Table',
      slug: 'Dining Table',
      cateogry: 'Furnitures',
      image: '/images/img3.jpg',
      price: 25000,
      countInStock: 10,
      brand: 'Star',
      rating: 4.5,
      numReviews: 10,
      description: '6 Seater Dining table American Walnut Finish',
    },
    {
      name: 'Watch',
      slug: 'watch',
      cateogry: 'Watches',
      image: '/images/img4.jpg',
      price: 18928,
      countInStock: 10,
      brand: 'Daniel Willington',
      rating: 4.5,
      numReviews: 10,
      description: 'Petite Melorse watch + Classic Bracelet',
    },
    {
      name: 'Shoes',
      slug: 'Shoes',
      cateogry: 'Sports shoes',
      image: '/images/img5.jpg',
      price: 8740,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Very comfy and attractive shoes',
    },
    {
      name: 'Light Lamp',
      slug: 'Light Lamp',
      cateogry: 'Household items',
      image: '/images/img6.jpg',
      price: 5400,
      countInStock: 5,
      brand: 'Star',
      rating: 3.9,
      numReviews: 10,
      description: 'White light lamp',
    },
    {
      name: 'Coffee Mugs',
      slug: 'Coffee Mugs',
      cateogry: 'Crockeries',
      image: '/images/img7.jpg',
      price: 647,
      countInStock: 15,
      brand: 'Star',
      rating: 4.7,
      numReviews: 10,
      description: 'Black 6 pieces solid ceramic coffee mug',
    },
  ],
};
export default data;
